spring:
  profiles:
    active: staging

  application:
    name: catalogo-musical-api

  jackson:
    time-zone: America/Sao_Paulo
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: true

  datasource:
    url: jdbc:postgresql://${DB_URL}:25060/${DB_NAME}?sslmode=require
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariCP-STAGING
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=10m

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

security:
  jwt:
    issuer: spring-security-jwt
    access-token-expiration: 5m
    refresh-token-expiration: 4h
    secret: ${JWT_SECRET}

server:
  port: 8080

application:
  name: @project.name@
  description: @project.description@
  env: ${spring.profiles.active}
  version: @project.version@
  endpoint: ${APPLICATION_ENDPOINT}

  integrations:
    minio:
      internal-endpoint: ${MINIO_INTERNAL_URL}
      public-endpoint: ${MINIO_PUBLIC_URL}
      access-key: ${MINIO_SECRET_KEY}
      secret-key: ${MINIO_ACCESS_KEY}
      bucket-name: ${MINIO_BUCKET}
      signature-duration: ${MINIO_SIGNATURE_DURATION}

    argus:
      endpoint: ${ARGUS-API.GEIA_ENDPOINT}

  scheduler:
    regional-sync:
      enabled: true
      cron: "0 0 */2 * * *"

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    org.hibernate: WARN
    org.hibernate.orm: WARN
    org.springframework: INFO
    org.springframework.security: INFO
    br.gov.mt.seplag: DEBUG
    com.zaxxer.hikari: INFO
